"""Single-writer canonical Event and transactional outbox foundation."""

from .memory import InMemoryEventStore, SimulatedCommitFailure
from .models import (
    EVENT_COMMAND_SCHEMA_VERSION,
    EVENT_DOMAIN_EVENT_VERSION,
    EVENT_PRODUCER,
    CanonicalEvent,
    CanonicalEventIdentity,
    ClassificationCertainty,
    ClassificationKind,
    ClassificationSource,
    CommandReceipt,
    CreateEventCommand,
    EventClassification,
    EventInputMetadata,
    EventStateLog,
    EventVersions,
    EventWriteDisposition,
    EventWriteResult,
    LineageRef,
    ReconcileEventCommand,
    TransitionLifecycleCommand,
    command_fingerprint,
)
from .outbox import (
    IdempotentOutboxTransport,
    OutboxMessage,
    OutboxPublisher,
    OutboxRecord,
    OutboxStatus,
    PublishBatchResult,
)
from .postgres import PostgresEventStore
from .store import (
    ConcurrentEventWriteError,
    EventIdentityConflictError,
    EventNotFoundError,
    EventStore,
    EventStoreError,
    EventTransaction,
    IdempotencyConflictError,
)
from .writer import EventWriter

__all__ = [
    "EVENT_COMMAND_SCHEMA_VERSION",
    "EVENT_DOMAIN_EVENT_VERSION",
    "EVENT_PRODUCER",
    "CanonicalEvent",
    "CanonicalEventIdentity",
    "ClassificationCertainty",
    "ClassificationKind",
    "ClassificationSource",
    "CommandReceipt",
    "ConcurrentEventWriteError",
    "CreateEventCommand",
    "EventClassification",
    "EventIdentityConflictError",
    "EventInputMetadata",
    "EventNotFoundError",
    "EventStateLog",
    "EventStore",
    "EventStoreError",
    "EventTransaction",
    "EventVersions",
    "EventWriteDisposition",
    "EventWriteResult",
    "EventWriter",
    "IdempotencyConflictError",
    "IdempotentOutboxTransport",
    "InMemoryEventStore",
    "LineageRef",
    "OutboxMessage",
    "OutboxPublisher",
    "OutboxRecord",
    "OutboxStatus",
    "PostgresEventStore",
    "PublishBatchResult",
    "ReconcileEventCommand",
    "SimulatedCommitFailure",
    "TransitionLifecycleCommand",
    "command_fingerprint",
]
